            - name: Cloud Storage Uploader
  # You may pin to the exact commit or the version.
  # uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77
  uses: google-github-actions/upload-cloud-storage@v2.1.0
  with:
    # Project ID to use for making requests. By default, this is extracted from
the running environment.
    project_id: # optional
    # The path to a file or folder inside the action's filesystem
that should be uploaded to the bucket.
You can specify either the absolute path or the relative path from the action.
    path: 
    # GCS bucket name of form <bucketname> or with an optional prefix
of form <bucketname>/<prefix>
    destination: 
    # Upload file(s) with gzip content encoding, defaults to true.
    gzip: # optional, default is true
    # Enable resumable uploads, defaults to true.
    resumable: # optional, default is true
    # Apply a predefined set of access controls to the file(s).
    predefinedAcl: # optional
    # Whether parent dir should be included in GCS destination, defaults to true.
    parent: # optional, default is true
    # Optional glob pattern.
    glob: # optional
    # Number of files to simultaneously upload.
    concurrency: # optional, default is 100
    # Set headers (object metadata).
    headers: # optional
    # Process the .gcloudignore file in the root of the repository and do not
upload files that match the patterns.
    process_gcloudignore: # optional, default is true
          
